import { PromptData, ExportFormat } from "@/types/prompt";

export async function exportPrompt(prompt: PromptData, format: ExportFormat): Promise<Blob> {
  switch (format) {
    case "json":
      return new Blob([JSON.stringify(prompt, null, 2)], { type: "application/json" });
    
    case "txt":
      return new Blob([prompt.text], { type: "text/plain" });
    
    case "markdown":
      return new Blob([`# ${prompt.title}\n\n${prompt.text}\n\n---\n\n**Модель:** ${prompt.model}\n**Качество:** ${prompt.quality}%\n**Дата:** ${new Date(prompt.createdAt).toLocaleDateString("ru-RU")}`], { type: "text/markdown" });
    
    case "code":
      return new Blob([`// Prompt generated by PromptCraft Studio\nconst prompt = \`${prompt.text.replace(/`/g, "\\`")}\`;\n\n// Metadata\nconst metadata = ${JSON.stringify(prompt.metadata, null, 2)};`], { type: "text/javascript" });
    
    case "png":
    case "pdf":
      throw new Error(`Export to ${format} requires additional library (html2canvas/jsPDF)`);
    
    default:
      throw new Error(`Unknown export format: ${format}`);
  }
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function exportAndDownload(prompt: PromptData, format: ExportFormat) {
  const extension: Record<ExportFormat, string> = {
    json: "json",
    txt: "txt",
    markdown: "md",
    code: "js",
    png: "png",
    pdf: "pdf",
  };
  
  const filename = `prompt-${prompt.id.slice(0, 8)}.${extension[format]}`;
  
  try {
    const blob = await exportPrompt(prompt, format);
    downloadBlob(blob, filename);
    return true;
  } catch (error) {
    console.error("Export failed:", error);
    return false;
  }
}

export function getExportFormatsForModel(model: string): ExportFormat[] {
  const textModels = ["yandexgpt", "gigachat"];
  const imageModels = ["kandinsky", "shedevrum"];
  
  if (textModels.includes(model)) {
    return ["json", "txt", "markdown", "code"];
  }
  
  if (imageModels.includes(model)) {
    return ["json", "txt", "png"];
  }
  
  return ["json", "txt"];
}